spring:
  datasource:
    username: root
    password: Aa-12345678
    url: jdbc:mysql://121.43.191.246/blockchain
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 8181